pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir ('starter') {
                    bat 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir ('starter') {
                    bat 'mvn -B test'
                }
            }

            post {
                    always {
                        dir ('starter') {
                            junit 'target/surefire-reports/*.xml'
                        }
                    }  
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'starter/target/*.jar', fingerprint: true
            }
        }
    }
}